version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_inventario
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=12345678#Aa
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_inventario
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASS=12345678#Aa
      - DB_NAME=inventario_db
    depends_on:
      - sqlserver

volumes:
  mssql_data:
